[project]
name = "didactic-eureka"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "nk225op>=0.1.9",
    "requests>=2.32.5",
    "yfinance>=0.2.65",
]
