[project]
name = "lambda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aws-xray-sdk>=2.14.0",
    "beautifulsoup4>=4.13.4",
    "boto3>=1.40.15",
    "pandas>=2.3.2",
]
